use_frameworks!

target 'TYDesignableLabel_Example' do
  pod 'TYDesignableLabel', :path => '../'

  target 'TYDesignableLabel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
